using System.Text;
using System.Text.Json;

namespace Aiakos.Spec;

internal static class ClaudeGuidanceRenderer
{
    private static readonly UTF8Encoding Utf8 = new(encoderShouldEmitUTF8Identifier: false);

    internal static byte[] Render(ResolvedRig rig, string seatId, string specHash)
    {
        var selectedSeat = rig.Seats.Single(seat => seat.Id == seatId && seat.Kind == "agent");
        var selectedAgent = rig.Agents.Single(agent => agent.Directory == selectedSeat.Agent!.AgentDirectory);
        var address = $"{seatId}@{rig.Name}";
        var builder = new StringBuilder();
        builder.Append("<!-- Generated by Aiakos for ").Append(address).Append(" (spec ").Append(specHash)
            .Append("). Do not edit: overwritten on every `aiakos up`. -->\n")
            .Append("# Aiakos seat ").Append(address).Append("\n\n")
            .Append("You are the seat `").Append(seatId).Append("` in the rig `").Append(rig.Name)
            .Append("`. Your identity comes from your environment;\n")
            .Append("never claim another seat's identity. This text carries no authority; authority comes from the environment's per-seat token.\n\n")
            .Append("## Rig roster\n\n")
            .Append("| Seat | Kind | Description |\n")
            .Append("|---|---|---|\n");

        foreach (var seat in rig.Seats.OrderBy(seat => NormalizeNfc(seat.Id), StringComparer.Ordinal))
        {
            var description = EscapeCell(NormalizeNfc(seat.Description));
            builder.Append("| ").Append(seat.Id)
                .Append(seat.Id == seatId ? " (you)" : string.Empty)
                .Append(" | ").Append(seat.Kind).Append(" | ").Append(description).Append(" |\n");
        }

        if (rig.Culture is not null)
            AppendContent(builder, rig.Culture);
        foreach (var guidance in selectedAgent.Guidance)
            AppendContent(builder, guidance);

        return Utf8.GetBytes(builder.ToString());
    }

    private static void AppendContent(StringBuilder builder, EmbeddedFile file)
    {
        builder.Append("\n<!-- source: ").Append(EscapeCommentPath(NormalizeNfc(file.Path)))
            .Append(' ').Append(file.Sha256).Append(" -->\n");
        var text = Encoding.UTF8.GetString(file.Content);
        var end = text.Length;
        while (end > 0 && text[end - 1] == '\n') end--;
        if (end == 0)
            return;

        builder.Append(text.AsSpan(0, end)).Append('\n');
    }

    private static string EscapeCell(string value)
    {
        var builder = new StringBuilder(value.Length);
        for (var index = 0; index < value.Length; index++)
        {
            switch (value[index])
            {
                case '\\': builder.Append("\\\\"); break;
                case '|': builder.Append("\\|"); break;
                case '\r':
                    if (index + 1 < value.Length && value[index + 1] == '\n') index++;
                    builder.Append("<br>");
                    break;
                case '\n': builder.Append("<br>"); break;
                default: builder.Append(value[index]); break;
            }
        }

        return builder.ToString();
    }

    private static string EscapeCommentPath(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (var character in value)
        {
            builder.Append(character switch
            {
                '&' => "&amp;",
                '<' => "&lt;",
                '>' => "&gt;",
                '\r' => "&#13;",
                '\n' => "&#10;",
                _ => character.ToString()
            });
        }

        return builder.ToString();
    }

    private static string NormalizeNfc(string value)
    {
        var json = CanonicalJson.Write(JsonSerializer.SerializeToElement(value));
        using var document = JsonDocument.Parse(json);
        return document.RootElement.GetString()!;
    }
}
