<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" />
    <PackageReference Include="Grpc.AspNetCore.HealthChecks" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Aiakos.Node\Aiakos.Node.csproj" />
  </ItemGroup>

</Project>
