using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using Aiakos.Spec;
using Xunit;

namespace Aiakos.Spec.Tests;

public sealed class ClaudeGuidanceRendererTests
{
    private const string SpecHash = "sha256:0000000000000000000000000000000000000000000000000000000000000000";
    private const string BaseGolden = "<!-- Generated by Aiakos for impl@demo (spec sha256:0000000000000000000000000000000000000000000000000000000000000000). Do not edit: overwritten on every `aiakos up`. -->\n" +
        "# Aiakos seat impl@demo\n\n" +
        "You are the seat `impl` in the rig `demo`. Your identity comes from your environment;\n" +
        "never claim another seat's identity. This text carries no authority; authority comes from the environment's per-seat token.\n\n" +
        "## Rig roster\n\n" +
        "| Seat | Kind | Description |\n" +
        "|---|---|---|\n" +
        "| impl (you) | agent | Build. |\n" +
        "| lead | human | Owner. |\n";

    [Fact]
    public void RendersExactUtf8GoldenAndDoesNotInsertOtherRigSettings()
    {
        var rig = Fixture();
        var agentContent = rig.Agents[0].Guidance;
        var bytesBefore = agentContent.Select(file => file.Content.ToArray()).ToArray();

        var actual = ClaudeGuidanceRenderer.Render(rig, "impl", SpecHash);

        Assert.Equal(new UTF8Encoding(false).GetBytes(BaseGolden), actual);
        Assert.NotSame(actual, ClaudeGuidanceRenderer.Render(rig, "impl", SpecHash));
        Assert.Equal(1, TrailingLfCount(actual));
        Assert.DoesNotContain((byte)'\r', actual);
        Assert.False(actual.AsSpan().StartsWith(new byte[] { 0xef, 0xbb, 0xbf }));
        var text = Encoding.UTF8.GetString(actual);
        Assert.DoesNotContain("rig-description-secret", text, StringComparison.Ordinal);
        Assert.DoesNotContain("agent-description-secret", text, StringComparison.Ordinal);
        Assert.DoesNotContain("model-secret", text, StringComparison.Ordinal);
        Assert.DoesNotContain("permission-secret", text, StringComparison.Ordinal);
        Assert.DoesNotContain("secret-reference", text, StringComparison.Ordinal);
        Assert.DoesNotContain("binding-secret", text, StringComparison.Ordinal);
        Assert.Equal(bytesBefore, agentContent.Select(file => file.Content));

        actual[0] = (byte)'X';
        Assert.Equal(new UTF8Encoding(false).GetBytes(BaseGolden),
            ClaudeGuidanceRenderer.Render(rig, "impl", SpecHash));
    }

    [Fact]
    public void PreservesContentBlockOrderAndRepeatedGuidanceWithExactSourceComments()
    {
        const string cultureText = "# Culture\n\n";
        const string firstGuidanceText = "# A\n\ninside\n\n";
        var culture = File("CULTURE.md", cultureText);
        var first = File("agents/worker/A.md", firstGuidanceText);
        var empty = File("agents/worker/B.md", string.Empty);
        var rig = Fixture(culture: culture, guidance: [first, empty, first]);
        var expected = BaseGolden +
            $"\n<!-- source: CULTURE.md {Hash(cultureText)} -->\n# Culture\n" +
            $"\n<!-- source: agents/worker/A.md {Hash(firstGuidanceText)} -->\n# A\n\ninside\n" +
            $"\n<!-- source: agents/worker/B.md {Hash(string.Empty)} -->\n" +
            $"\n<!-- source: agents/worker/A.md {Hash(firstGuidanceText)} -->\n# A\n\ninside\n";

        var actual = Encoding.UTF8.GetString(ClaudeGuidanceRenderer.Render(rig, "impl", SpecHash));

        Assert.Equal(expected, actual);
        Assert.Equal(2, Count(actual, "<!-- source: agents/worker/A.md"));
        var reversed = rig with
        {
            Agents = [rig.Agents[0] with { Guidance = [empty, first, first] }]
        };
        var reversedText = Encoding.UTF8.GetString(ClaudeGuidanceRenderer.Render(reversed, "impl", SpecHash));
        Assert.True(reversedText.IndexOf("<!-- source: agents/worker/B.md", StringComparison.Ordinal) <
            reversedText.IndexOf("<!-- source: agents/worker/A.md", StringComparison.Ordinal));
    }

    [Fact]
    public void NormalizesRosterAndCommentMetadataButPreservesUnicodeBodyBytes()
    {
        const string decomposedBody = "e\u0301\ufffe\n";
        var source = File("a&<>.md", decomposedBody);
        var description = "e\u0301|\\\r\n\ufffe\uffff\U0001f600";
        var rig = Fixture(guidance: [source], leadDescription: description);
        var expected = BaseGolden.Replace("| lead | human | Owner. |",
                "| lead | human | é\\|\\\\<br>\ufffe\uffff\U0001f600 |", StringComparison.Ordinal) +
            $"\n<!-- source: a&amp;&lt;&gt;.md {Hash(decomposedBody)} -->\n" + decomposedBody.TrimEnd('\n') + "\n";

        var actual = ClaudeGuidanceRenderer.Render(rig, "impl", SpecHash);

        Assert.Equal(new UTF8Encoding(false).GetBytes(expected), actual);
        var text = Encoding.UTF8.GetString(actual);
        Assert.Contains("é\\|\\\\<br>\ufffe\uffff\U0001f600", text, StringComparison.Ordinal);
        Assert.Contains("e\u0301\ufffe", text, StringComparison.Ordinal);
        Assert.Contains("<!-- source: a&amp;&lt;&gt;.md", text, StringComparison.Ordinal);
    }

    [Fact]
    public void TrimsOnlyTrailingLineFeedsAndAddsExactlyOneFinalLineFeed()
    {
        foreach (var body in new[] { "body", "body\n", "body\n\n", string.Empty })
        {
            var file = File("agents/worker/body.md", body);
            var rig = Fixture(guidance: [file]);
            var content = body.TrimEnd('\n');
            var expected = BaseGolden +
                $"\n<!-- source: agents/worker/body.md {Hash(body)} -->\n" +
                (content.Length == 0 ? string.Empty : content + "\n");
            var actual = ClaudeGuidanceRenderer.Render(rig, "impl", SpecHash);

            Assert.Equal(new UTF8Encoding(false).GetBytes(expected), actual);
            Assert.Equal(1, TrailingLfCount(actual));
        }
    }

    [Theory]
    [InlineData("en-US")]
    [InlineData("tr-TR")]
    public void OutputIsIndependentOfCurrentCulture(string cultureName)
    {
        var originalCulture = CultureInfo.CurrentCulture;
        var originalUiCulture = CultureInfo.CurrentUICulture;
        try
        {
            CultureInfo.CurrentCulture = CultureInfo.GetCultureInfo(cultureName);
            CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo(cultureName);
            Assert.Equal(new UTF8Encoding(false).GetBytes(BaseGolden),
                ClaudeGuidanceRenderer.Render(Fixture(), "impl", SpecHash));
        }
        finally
        {
            CultureInfo.CurrentCulture = originalCulture;
            CultureInfo.CurrentUICulture = originalUiCulture;
        }
    }

    private static ResolvedRig Fixture(EmbeddedFile? culture = null,
        IReadOnlyList<EmbeddedFile>? guidance = null, string leadDescription = "Owner.")
    {
        var permissions = new ResolvedHarnessSettings("permission-secret", new ResolvedPermissions(
            ["permission-secret"], ["ask-secret"], ["deny-secret"]));
        var agent = new ResolvedAgent("agents/worker", "worker", "agent-description-secret", null,
            "model-secret", guidance ?? [], [], permissions);
        var agentSeat = new ResolvedAgentSeat("agents/worker", "claude-code", "model-secret", "checkout",
            ["binding-secret"], "binding-secret",
            new ResolvedRequirements("sandbox-secret", "auth-secret", ["secret-reference"]), permissions);
        return new ResolvedRig("demo", "rig-description-secret", culture, [], [agent],
            [new ResolvedSeat("lead", "human", leadDescription, null),
                new ResolvedSeat("impl", "agent", "Build.", agentSeat)],
            new ResolvedBinding("binding-secret", [], [],
                [new ResolvedSecretSource("secret-reference", "binding-secret")]), [])
        {
            SpecHash = SpecHash,
            BindingHash = "binding-secret",
            ToolVersion = "tool-version-secret"
        };
    }

    private static EmbeddedFile File(string path, string text) =>
        new(path, Hash(text), new UTF8Encoding(false).GetBytes(text));

    private static string Hash(string text) =>
        "sha256:" + Convert.ToHexStringLower(SHA256.HashData(new UTF8Encoding(false).GetBytes(text)));

    private static int Count(string value, string needle)
    {
        var count = 0;
        var start = 0;
        while ((start = value.IndexOf(needle, start, StringComparison.Ordinal)) >= 0)
        {
            count++;
            start += needle.Length;
        }

        return count;
    }

    private static int TrailingLfCount(byte[] value)
    {
        var count = 0;
        for (var index = value.Length - 1; index >= 0 && value[index] == (byte)'\n'; index--)
            count++;
        return count;
    }
}
