using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Aiakos.Spec;

namespace Aiakos.Spec.Tests;

public sealed class LoadProjectionIntegrationTests
{
    private static readonly string[] ExpectedAgentSeats = ["impl", "review"];
    private static readonly string[] ExpectedPlanFiles = ["CLAUDE.md"];
    private static readonly string[] ExpectedSkillPlanFiles =
        [".claude/skills/build/.metadata", ".claude/skills/build/SKILL.md", "CLAUDE.md"];

    [Fact]
    public void SuccessfulLoadAddsPlansForAgentSeatsWithFinalizedHashes()
    {
        using var fixture = new FullFixture();
        var result = RigLoader.Load(fixture.Root, null);

        Assert.NotNull(result.Rig);
        Assert.Empty(result.Diagnostics);
        Assert.Equal(result.Rig.Canonical!.SpecHash, result.Rig.SpecHash);
        Assert.Equal(result.Rig.Canonical.BindingHash, result.Rig.BindingHash);
        Assert.Equal(ExpectedAgentSeats, result.Rig.SeatParameters.Select(item => item.Seat));
        Assert.All(result.Rig.SeatParameters, parameters =>
        {
            Assert.Equal(result.Rig.SpecHash, parameters.SpecHash);
            Assert.Equal(result.Rig.BindingHash, parameters.BindingHash);
        });

        using var json = JsonDocument.Parse(JsonSerializer.Serialize(result.Rig));
        var seats = json.RootElement.GetProperty("SeatParameters").EnumerateArray().ToArray();
        Assert.Equal(2, seats.Length);
        Assert.Equal("~/aiakos/seats/demo/impl/projection",
            seats[0].GetProperty("Projection").GetProperty("Root").GetString());
        Assert.Equal("~/aiakos/seats/demo/review/projection",
            seats[1].GetProperty("Projection").GetProperty("Root").GetString());
        Assert.Equal("BindingHash", seats[0].EnumerateObject().Select(property => property.Name).ElementAt(14));
        Assert.Equal("Projection", seats[0].EnumerateObject().Select(property => property.Name).Last());

        var impl = seats[0].GetProperty("Projection");
        var specHash = result.Rig.SpecHash!;
        var expectedText = $"<!-- Generated by Aiakos for impl@demo (spec {specHash}). Do not edit: overwritten on every `aiakos up`. -->\n" +
            "# Aiakos seat impl@demo\n\n" +
            "You are the seat `impl` in the rig `demo`. Your identity comes from your environment;\n" +
            "never claim another seat's identity. This text carries no authority; authority comes from the environment's per-seat token.\n\n" +
            "## Rig roster\n\n| Seat | Kind | Description |\n|---|---|---|\n" +
            "| impl (you) | agent | Implements issues |\n" +
            "| pm | human | Product owner |\n" +
            "| review | agent | Implements issues |\n";
        Assert.Equal(ExpectedPlanFiles, impl.GetProperty("Files").EnumerateArray()
            .Select(file => file.GetProperty("Path").GetString()));
        var clause = Assert.Single(impl.GetProperty("Files").EnumerateArray());
        var actualText = Encoding.UTF8.GetString(Convert.FromBase64String(
            impl.GetProperty("Contents").GetProperty(clause.GetProperty("Sha256").GetString()!).GetString()!));
        Assert.Equal(expectedText, actualText);
        Assert.Equal(Encoding.UTF8.GetByteCount(expectedText), clause.GetProperty("Bytes").GetInt32());
        var contentHash = Hash(Encoding.UTF8.GetBytes(expectedText));
        Assert.Equal(contentHash, clause.GetProperty("Sha256").GetString());
        var canonical = "[{\"bytes\":" + Encoding.UTF8.GetByteCount(expectedText) +
            ",\"mode\":\"0644\",\"path\":\"CLAUDE.md\",\"sha256\":\"" + contentHash + "\"}]";
        Assert.Equal(Hash(Encoding.UTF8.GetBytes(canonical)), impl.GetProperty("Hash").GetString());

        var alternate = fixture.Write("alternate.env.yaml", File.ReadAllText(
            Path.Combine(fixture.Root, "rig.env.yaml"), Encoding.UTF8)
            .Replace("~/aiakos/seats", "/alternate/seats", StringComparison.Ordinal)
            .Replace("default_node: local", "default_node: remote", StringComparison.Ordinal)
            .Replace("/home/dev/app", "/alternate/app", StringComparison.Ordinal)
            .Replace("~/src/lib", "/alternate/lib", StringComparison.Ordinal));
        var changedBinding = RigLoader.Load(fixture.Root, alternate);
        Assert.NotNull(changedBinding.Rig);
        Assert.Equal(result.Rig.SpecHash, changedBinding.Rig.SpecHash);
        Assert.NotEqual(result.Rig.BindingHash, changedBinding.Rig.BindingHash);
        Assert.Equal(impl.GetProperty("Hash").GetString(), GetProjection(changedBinding.Rig, "impl").Hash);
        Assert.Equal("/alternate/seats/demo/impl/projection", GetProjection(changedBinding.Rig, "impl").Root);
    }

    [Fact]
    public void LoadEmbedsGuidanceAndMapsSkillSnapshotBytesIntoEachPlan()
    {
        using var fixture = new FullFixture();
        const string culture = "Team.\n";
        const string guidance = "# Guide\n\nBody\n";
        byte[] skill = [0xef, 0xbb, 0xbf, .. Encoding.UTF8.GetBytes("---\nname: build\ndescription: builds\n---\n")];
        byte[] metadata = [0, 255, 1];
        fixture.Write("culture.md", culture);
        fixture.Append("rig.yaml", "culture_file: culture.md\n");
        fixture.Write("agents/impl/guide.md", guidance);
        fixture.Append("agents/impl/agent.yaml", "guidance: [guide.md]\nskills: [skills/build]\n");
        fixture.WriteBytes("agents/impl/skills/build/SKILL.md", skill);
        fixture.WriteBytes("agents/impl/skills/build/.metadata", metadata);
        var sourceBefore = fixture.Snapshot();

        var result = RigLoader.Load(fixture.Root, null);

        Assert.True(result.Rig is not null, DiagnosticFormatter.Format(result.Diagnostics));
        Assert.Empty(result.Diagnostics);
        Assert.Equal(sourceBefore, fixture.Snapshot());
        foreach (var parameters in result.Rig.SeatParameters)
        {
            var plan = parameters.Projection!;
            Assert.Equal(ExpectedSkillPlanFiles, plan.Files.Select(file => file.Path));
            Assert.All(plan.Files, file => Assert.Equal("0644", file.Mode));
            Assert.Equal(Hash(skill), plan.Files.Single(file => file.Path.EndsWith("SKILL.md", StringComparison.Ordinal)).Sha256);
            Assert.Equal(Hash(metadata), plan.Files.Single(file => file.Path.EndsWith(".metadata", StringComparison.Ordinal)).Sha256);
            Assert.Equal(skill, plan.Contents[Hash(skill)]);
            Assert.Equal(metadata, plan.Contents[Hash(metadata)]);

            var body = Guidance(parameters.Seat, result.Rig.SpecHash!, culture, guidance);
            var bodyHash = Hash(Encoding.UTF8.GetBytes(body));
            var generated = plan.Files.Single(file => file.Path == "CLAUDE.md");
            Assert.Equal(bodyHash, generated.Sha256);
            Assert.Equal(Encoding.UTF8.GetByteCount(body), generated.Bytes);
            Assert.Equal(Encoding.UTF8.GetBytes(body), plan.Contents[generated.Sha256]);
            var expectedDescriptors = "[{\"bytes\":" + metadata.Length +
                ",\"mode\":\"0644\",\"path\":\".claude/skills/build/.metadata\",\"sha256\":\"" + Hash(metadata) +
                "\"},{\"bytes\":" + skill.Length +
                ",\"mode\":\"0644\",\"path\":\".claude/skills/build/SKILL.md\",\"sha256\":\"" + Hash(skill) +
                "\"},{\"bytes\":" + Encoding.UTF8.GetByteCount(body) +
                ",\"mode\":\"0644\",\"path\":\"CLAUDE.md\",\"sha256\":\"" + bodyHash + "\"}]";
            Assert.Equal(Hash(Encoding.UTF8.GetBytes(expectedDescriptors)), plan.Hash);
        }
    }

    [Fact]
    public void LoadReportsOversizedPlansForEachSeatAtItsIdScalarInOrder()
    {
        const string rigText = "apiVersion: aiakos.dev/v1\n" +
            "kind: Rig\n" +
            "name: demo\n" +
            "workspace: {repos: [{name: app, url: https://example.com/app.git}]}\n" +
            "# two agent seats share the embedded snapshot\n" +
            "# the generated plans are each over the size limit\n" +
            "seats:\n" +
            "  - id: impl\n" +
            "    agent_ref: local:agents/impl\n" +
            "    harness: claude-code\n" +
            "  - id: review\n" +
            "    agent_ref: local:agents/impl\n" +
            "    harness: claude-code\n";
        using var fixture = new LargeFixture(rigText);
        foreach (var index in Enumerable.Range(0, 9))
            fixture.Write($"large-{index}.md", new string('a', 262144));

        var result = RigLoader.Load(fixture.Root, null);

        Assert.Null(result.Rig);
        Assert.Equal("rig.yaml:8:9: error AIK3005: projection exceeds 2 MiB\n" +
            "rig.yaml:11:9: error AIK3005: projection exceeds 2 MiB\n",
            DiagnosticFormatter.Format(result.Diagnostics));
    }

    [Fact]
    public void LoadChecksUnselectedBindingsForProjectionOverlap()
    {
        using var fixture = new FullFixture();
        fixture.Write("rig.yaml", "apiVersion: aiakos.dev/v1\n" +
            "kind: Rig\n" +
            "name: demo\n" +
            "workspace: {repos: [{name: app, url: https://example.com/app.git}, {name: lib, url: https://example.com/lib.git}]}\n" +
            "# selected and unselected repositories have different nodes\n" +
            "# every environment binding is checked for each projection\n" +
            "seats:\n" +
            "  - id: impl\n" +
            "    agent_ref: local:agents/impl\n" +
            "    checkout: shared\n" +
            "    repos: [app]\n" +
            "  - id: review\n" +
            "    agent_ref: local:agents/impl\n" +
            "    checkout: shared\n" +
            "    repos: [lib]\n");
        fixture.Write("rig.env.yaml", "apiVersion: aiakos.dev/v1\n" +
            "kind: RigEnv\n" +
            "rig: demo\n" +
            "seat_root: /seats\n" +
            "placement:\n" +
            "  default_node: local\n" +
            "  seats:\n" +
            "    review: {node: remote}\n" +
            "repos:\n" +
            "  app: {path: /checkouts/app}\n" +
            "  lib: {path: /seats/demo/impl/projection}\n");

        var result = RigLoader.Load(fixture.Root, null);

        Assert.Null(result.Rig);
        var diagnostic = Assert.Single(result.Diagnostics);
        Assert.Equal(new Diagnostic(Severity.Error, "AIK3002", "rig.yaml", 8, 9,
            "projection root overlaps a repository checkout", null), diagnostic);
    }

    [Fact]
    public void EarlierLoadErrorsSuppressProjectionDiagnostics()
    {
        const string rigText = "apiVersion: aiakos.dev/v1\n" +
            "kind: Rig\n" +
            "name: demo\n" +
            "workspace: {repos: [{name: app, url: https://example.com/app.git}]}\n" +
            "invalid_field: value\n" +
            "seats:\n" +
            "  - id: impl\n" +
            "    agent_ref: local:agents/impl\n" +
            "    harness: claude-code\n";
        using var fixture = new LargeFixture(rigText);
        foreach (var index in Enumerable.Range(0, 9))
            fixture.Write($"large-{index}.md", new string('a', 262144));

        var result = RigLoader.Load(fixture.Root, null);

        Assert.Null(result.Rig);
        Assert.Contains(result.Diagnostics, diagnostic => diagnostic.Severity == Severity.Error);
        Assert.DoesNotContain(result.Diagnostics, diagnostic => diagnostic.Code is "AIK3005" or "AIK3002");
    }

    private static string Hash(byte[] bytes) =>
        "sha256:" + Convert.ToHexStringLower(SHA256.HashData(bytes));

    private static ResolvedProjection GetProjection(ResolvedRig rig, string seat) =>
        rig.SeatParameters.Single(item => item.Seat == seat).Projection!;

    private static string Guidance(string selectedSeat, string specHash, string culture, string guidance)
    {
        var rows = "| impl" + (selectedSeat == "impl" ? " (you)" : "") + " | agent | Implements issues |\n" +
            "| pm | human | Product owner |\n" +
            "| review" + (selectedSeat == "review" ? " (you)" : "") + " | agent | Implements issues |\n";
        return $"<!-- Generated by Aiakos for {selectedSeat}@demo (spec {specHash}). Do not edit: overwritten on every `aiakos up`. -->\n" +
            $"# Aiakos seat {selectedSeat}@demo\n\n" +
            $"You are the seat `{selectedSeat}` in the rig `demo`. Your identity comes from your environment;\n" +
            "never claim another seat's identity. This text carries no authority; authority comes from the environment's per-seat token.\n\n" +
            "## Rig roster\n\n| Seat | Kind | Description |\n|---|---|---|\n" + rows +
            $"\n<!-- source: culture.md {Hash(Encoding.UTF8.GetBytes(culture))} -->\nTeam.\n" +
            $"\n<!-- source: agents/impl/guide.md {Hash(Encoding.UTF8.GetBytes(guidance))} -->\n# Guide\n\nBody\n";
    }

    private sealed class FullFixture : IDisposable
    {
        private static readonly string Source = Path.Combine(AppContext.BaseDirectory, "Fixtures", "valid", "full");

        public FullFixture()
        {
            Root = Path.Combine(Path.GetTempPath(), "full-projection-" + Guid.NewGuid().ToString("N"));
            CopyDirectory(Source, Root);
        }

        public string Root { get; }

        public string Write(string relative, string content)
        {
            var path = GetPath(relative);
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllText(path, content, new UTF8Encoding(false));
            return path;
        }

        public void Append(string relative, string content) => File.AppendAllText(GetPath(relative), content, new UTF8Encoding(false));

        public void WriteBytes(string relative, byte[] content)
        {
            var path = GetPath(relative);
            Directory.CreateDirectory(Path.GetDirectoryName(path)!);
            File.WriteAllBytes(path, content);
        }

        public string[] Snapshot() => Directory.GetFiles(Root, "*", SearchOption.AllDirectories)
            .Order(StringComparer.Ordinal).Select(path => Path.GetRelativePath(Root, path) + ":" + Hash(File.ReadAllBytes(path)))
            .ToArray();

        public void Dispose()
        {
            if (Directory.Exists(Root)) Directory.Delete(Root, recursive: true);
        }

        private string GetPath(string relative) => Path.Combine(Root, relative.Replace('/', Path.DirectorySeparatorChar));

        private static void CopyDirectory(string source, string destination)
        {
            Directory.CreateDirectory(destination);
            foreach (var file in Directory.GetFiles(source))
                File.Copy(file, Path.Combine(destination, Path.GetFileName(file)));
            foreach (var directory in Directory.GetDirectories(source))
                CopyDirectory(directory, Path.Combine(destination, Path.GetFileName(directory)));
        }
    }

    private sealed class LargeFixture : IDisposable
    {
        public LargeFixture(string rig)
        {
            Root = Path.Combine(Path.GetTempPath(), "large-projection-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(Path.Combine(Root, "agents", "impl"));
            File.WriteAllText(Path.Combine(Root, "rig.yaml"), rig, new UTF8Encoding(false));
            File.WriteAllText(Path.Combine(Root, "agents", "impl", "agent.yaml"),
                "apiVersion: aiakos.dev/v1\nkind: Agent\nname: impl\ndescription: Impl\ndefaults:\n  harness: claude-code\nguidance:\n" +
                string.Concat(Enumerable.Range(0, 9).Select(index => $"  - large-{index}.md\n")), new UTF8Encoding(false));
            File.WriteAllText(Path.Combine(Root, "rig.env.yaml"),
                "apiVersion: aiakos.dev/v1\nkind: RigEnv\nrig: demo\nplacement:\n  default_node: local\n" +
                "repos:\n  app:\n    path: /checkout/repo\n", new UTF8Encoding(false));
        }

        public string Root { get; }

        public void Write(string relative, string content) =>
            File.WriteAllText(Path.Combine(Root, "agents", "impl", relative), content, new UTF8Encoding(false));

        public void Dispose()
        {
            if (Directory.Exists(Root)) Directory.Delete(Root, recursive: true);
        }
    }
}
