using System.Collections.ObjectModel;
using System.Text;
using Aiakos.Core;
using Microsoft.Extensions.Logging;

namespace Aiakos.Node.Sessions;

public sealed class TmuxClient
{
    private const double MaximumTimeoutMilliseconds = 4294967294d;
    private const string MissingTmuxReason = "tmux executable could not be started; requires tmux >= 3.4.";
    private const string UnrecognizedVersionReason = "Unrecognized tmux version; requires tmux >= 3.4.";
    private const string ConfigurationFailureReason = "tmux configuration could not be prepared.";
    private static readonly string[] BaseEnvironmentNames =
    [
        "HOME", "USER", "LOGNAME", "SHELL", "PATH", "TMUX_TMPDIR", "XDG_RUNTIME_DIR"
    ];
    private static readonly HashSet<string> AllowedBaseEnvironmentNames =
        new(BaseEnvironmentNames, StringComparer.Ordinal);
    private static readonly Action<ILogger, string, Exception?> LogExecutable =
        LoggerMessage.Define<string>(LogLevel.Information, new EventId(0, nameof(LogExecutable)), "tmux executable: {Path}");
    private static readonly Action<ILogger, string, Exception?> LogRemovedEnvironment =
        LoggerMessage.Define<string>(LogLevel.Information, new EventId(0, nameof(LogRemovedEnvironment)), "Removed tmux global environment variable {Name}.");
    private static readonly (string Name, string Value)[] ServerOptions =
    [
        ("remain-on-exit", "on"),
        ("history-limit", "10000"),
        ("window-size", "manual"),
        ("update-environment", ""),
        ("allow-rename", "off"),
        ("automatic-rename", "off")
    ];
    private static readonly IReadOnlyList<string> AvailableCapabilities =
        Array.AsReadOnly(new[] { "session-host.tmux" });
    private static readonly string Configuration = string.Join("\n", new[]
    {
        "# Generated by aiakos-node. Do not edit; rewritten at every node start.",
        "set-option -g remain-on-exit on # keep dead panes: exit status and evidence",
        "set-option -g history-limit 10000 # scrollback for CapturePane",
        "set-option -g window-size manual # attaching humans do not resize seats",
        "set-option -g update-environment \"\" # attaching clients do not inject variables",
        "set-option -g allow-rename off # preserve managed names",
        "set-option -g automatic-rename off # preserve managed names"
    }) + "\n";

    private readonly object _initializationSync = new();
    private readonly string _configPath;
    private readonly string _socketName;
    private readonly string? _explicitTmuxPath;
    private readonly TimeSpan _invocationTimeout;
    private readonly ReadOnlyDictionary<string, string> _nodeEnvironment;
    private readonly IReadOnlyDictionary<string, string> _clientEnvironment;
    private readonly HashSet<string> _clientEnvironmentNames;
    private readonly IProcessRunner _runner;
    private readonly LaunchFiles _files;
    private readonly ILogger<TmuxClient> _logger;
    private Task? _initialization;
    private string? _resolvedPath;
    private SessionHostInfo _info = new("tmux", null, SessionHostAvailability.Unavailable,
        "tmux session host is not initialized.", Array.Empty<string>());

    public TmuxClient(TmuxHostOptions options, IProcessRunner runner,
        IReadOnlyDictionary<string, string> nodeEnvironment, ILogger<TmuxClient> logger,
        System.Diagnostics.Metrics.IMeterFactory meterFactory)
    {
        ArgumentNullException.ThrowIfNull(options);
        ArgumentNullException.ThrowIfNull(runner);
        ArgumentNullException.ThrowIfNull(nodeEnvironment);
        ArgumentNullException.ThrowIfNull(logger);
        ArgumentNullException.ThrowIfNull(meterFactory);

        try
        {
            _socketName = TmuxNames.SocketName(options.Instance);
            _configPath = TmuxNames.ConfigPath(options.Home);
        }
        catch (ArgumentException)
        {
            throw InvalidOptions();
        }

        if (options.InvocationTimeout <= TimeSpan.Zero ||
            options.InvocationTimeout.TotalMilliseconds > MaximumTimeoutMilliseconds ||
            options.TmuxPath is not null && !Path.IsPathFullyQualified(options.TmuxPath))
            throw InvalidOptions();

        _explicitTmuxPath = options.TmuxPath;
        _invocationTimeout = options.InvocationTimeout;
        _nodeEnvironment = new ReadOnlyDictionary<string, string>(
            new Dictionary<string, string>(nodeEnvironment, StringComparer.Ordinal));
        _clientEnvironment = BuildClientEnvironment(_nodeEnvironment);
        _clientEnvironmentNames = new HashSet<string>(_clientEnvironment.Keys, StringComparer.Ordinal);
        _runner = runner;
        _files = new LaunchFiles();
        _logger = logger;
    }

    public SessionHostInfo Info => _info;

    public Task InitializeAsync(CancellationToken ct)
    {
        lock (_initializationSync)
            return _initialization ??= InitializeCoreAsync(ct);
    }

    public async Task<ProcessResult> RunAsync(IReadOnlyList<string> command, ReadOnlyMemory<byte>? stdin,
        CancellationToken ct)
    {
        ArgumentNullException.ThrowIfNull(command);
        ct.ThrowIfCancellationRequested();
        EnsureAvailable();
        return await InvokeCommandAsync(command, stdin, ct).ConfigureAwait(false);
    }

    public static bool IsNoServer(ProcessResult result)
    {
        ArgumentNullException.ThrowIfNull(result);
        if (result.Outcome != ProcessOutcome.Exited || result.ExitCode is null or 0)
            return false;

        var stderr = Encoding.UTF8.GetString(result.Stderr);
        if (stderr.Contains("no server running", StringComparison.OrdinalIgnoreCase))
            return true;
        return stderr.Contains("error connecting to", StringComparison.OrdinalIgnoreCase) &&
               (stderr.Contains("(No such file or directory)", StringComparison.OrdinalIgnoreCase) ||
                stderr.Contains("(Connection refused)", StringComparison.OrdinalIgnoreCase));
    }

    public static SessionHostError? GetError(ProcessResult result)
    {
        ArgumentNullException.ThrowIfNull(result);
        if (result.Outcome == ProcessOutcome.TimedOut)
            return new SessionHostError(SessionHostErrorCode.TmuxTimeout, "tmux invocation timed out.", true);
        if (result.Outcome == ProcessOutcome.StartFailed)
            return new SessionHostError(SessionHostErrorCode.Unavailable, MissingTmuxReason, false);
        if (result.ExitCode == 0)
            return null;

        var stderr = Encoding.UTF8.GetString(result.Stderr);
        if (IsNoServer(result))
            return new SessionHostError(SessionHostErrorCode.TmuxFailed, "tmux server is not running.", true);
        if (stderr.Contains("can't find session", StringComparison.OrdinalIgnoreCase) ||
            stderr.Contains("can't find pane", StringComparison.OrdinalIgnoreCase))
            return new SessionHostError(SessionHostErrorCode.NotFound, "Session was not found.", false);
        if (stderr.Contains("duplicate session", StringComparison.OrdinalIgnoreCase))
            return new SessionHostError(SessionHostErrorCode.AlreadyRunning,
                "A live session already exists for SeatId.", false);

        var bytes = result.Stderr.AsSpan(0, Math.Min(result.Stderr.Length, 1024));
        var metadata = new ReadOnlyDictionary<string, string>(
            new Dictionary<string, string>(StringComparer.Ordinal) { ["stderr"] = Encoding.UTF8.GetString(bytes) });
        return new SessionHostError(SessionHostErrorCode.TmuxFailed, "tmux invocation failed.", true, metadata);
    }

    internal static IReadOnlyList<string> BuildCommandArguments(string configPath, string socketName,
        IReadOnlyList<string> command)
    {
        var arguments = new List<string>(5 + command.Count)
        {
            "-u", "-f", configPath, "-L", socketName
        };
        for (var index = 0; index < command.Count; index++)
        {
            var value = command[index];
            arguments.Add(index > 0 && value.EndsWith(';')
                ? value[..^1] + "\\;"
                : value);
        }
        return arguments.AsReadOnly();
    }

    private async Task InitializeCoreAsync(CancellationToken ct)
    {
        if (!OperatingSystem.IsLinux())
        {
            SetUnavailable("tmux session host requires Linux.");
            return;
        }

        _resolvedPath = ResolveTmuxPath();
        if (_resolvedPath is null)
        {
            SetUnavailable(MissingTmuxReason);
            return;
        }
        LogExecutable(_logger, _resolvedPath, null);

        var versionResult = await _runner.RunAsync(
            new ProcessRequest(_resolvedPath, ["-V"], _clientEnvironment, null, _invocationTimeout), ct)
            .ConfigureAwait(false);
        var versionError = GetError(versionResult);
        if (versionError is not null)
        {
            SetUnavailable(versionError.Message);
            return;
        }

        if (!TmuxVersion.TryParse(Encoding.UTF8.GetString(versionResult.Stdout),
                out var major, out var minor, out var version))
        {
            SetUnavailable(UnrecognizedVersionReason);
            return;
        }
        if (major < 3 || major == 3 && minor < 4)
        {
            SetUnavailable($"tmux {version} < 3.4", version);
            return;
        }

        try
        {
            ct.ThrowIfCancellationRequested();
            Directory.CreateDirectory(Path.GetDirectoryName(_configPath)!);
            File.WriteAllText(_configPath, Configuration, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException or
                                           ArgumentException or NotSupportedException)
        {
            SetUnavailable(ConfigurationFailureReason, version);
            return;
        }

        var environmentResult = await InvokeCommandAsync(["show-environment", "-g"], null, ct)
            .ConfigureAwait(false);
        if (IsNoServer(environmentResult))
        {
            SetAvailable(version);
            return;
        }

        var environmentError = environmentResult.Outcome == ProcessOutcome.Exited && environmentResult.ExitCode != 0
            ? null
            : GetError(environmentResult);
        if (environmentError is not null)
        {
            SetUnavailable(environmentError.Message, version);
            return;
        }

        foreach (var name in ParseEnvironmentNames(environmentResult.Stdout))
        {
            if (AllowedBaseEnvironmentNames.Contains(name) || _clientEnvironmentNames.Contains(name))
                continue;

            var unsetResult = await InvokeCommandAsync(["set-environment", "-g", "-u", name], null, ct)
                .ConfigureAwait(false);
            var unsetError = GetError(unsetResult);
            if (unsetError is not null)
            {
                SetUnavailable(unsetError.Message, version);
                return;
            }
            LogRemovedEnvironment(_logger, name, null);
        }

        foreach (var (name, value) in ServerOptions)
        {
            var optionResult = await InvokeCommandAsync(["set-option", "-g", name, value], null, ct)
                .ConfigureAwait(false);
            var optionError = GetError(optionResult);
            if (optionError is not null)
            {
                SetUnavailable(optionError.Message, version);
                return;
            }
        }

        SetAvailable(version);
    }

    private async Task<ProcessResult> InvokeCommandAsync(IReadOnlyList<string> command,
        ReadOnlyMemory<byte>? stdin, CancellationToken ct)
    {
        if (command.Count == 0 || string.IsNullOrEmpty(command[0]))
            throw new ArgumentException("A tmux command is required.", nameof(command));
        if (stdin is not null && command[0] != "load-buffer")
            throw new ArgumentException("Stdin is only supported by load-buffer.", nameof(stdin));

        var timeout = command[0] == "load-buffer"
            ? TimeSpan.FromTicks(TimeSpan.FromSeconds(5).Ticks +
                                 (long)(TimeSpan.TicksPerSecond * 2d * (stdin?.Length ?? 0) / 1048576d))
            : _invocationTimeout;
        var arguments = BuildCommandArguments(_configPath, _socketName, command);
        return await _runner.RunAsync(new ProcessRequest(_resolvedPath!, arguments, _clientEnvironment, stdin, timeout), ct)
            .ConfigureAwait(false);
    }

    private string? ResolveTmuxPath()
    {
        if (_explicitTmuxPath is not null)
            return _files.ExecutableExists(_explicitTmuxPath) ? _explicitTmuxPath : null;

        if (!_nodeEnvironment.TryGetValue("PATH", out var path))
            return null;
        foreach (var entry in path.Split(Path.PathSeparator, StringSplitOptions.None))
        {
            if (entry.Length == 0 || !Path.IsPathFullyQualified(entry))
                continue;
            var candidate = Path.Combine(entry, "tmux");
            if (_files.ExecutableExists(candidate))
                return candidate;
        }
        return null;
    }

    private static ReadOnlyDictionary<string, string> BuildClientEnvironment(
        ReadOnlyDictionary<string, string> nodeEnvironment)
    {
        var environment = new Dictionary<string, string>(StringComparer.Ordinal);
        foreach (var name in BaseEnvironmentNames)
            if (nodeEnvironment.TryGetValue(name, out var value))
                environment.Add(name, value);

        if (nodeEnvironment.TryGetValue("LC_ALL", out var lcAll) && lcAll.Length > 0 && IsUtf8Locale(lcAll))
        {
            environment.Add("LC_ALL", lcAll);
        }
        else if ((!nodeEnvironment.TryGetValue("LC_ALL", out lcAll) || lcAll.Length == 0) &&
                 nodeEnvironment.TryGetValue("LANG", out var lang) && IsUtf8Locale(lang))
        {
            environment.Add("LANG", lang);
        }
        else
        {
            environment.Add("LANG", "C.UTF-8");
        }

        return new ReadOnlyDictionary<string, string>(environment);
    }

    private static bool IsUtf8Locale(string locale) =>
        locale.EndsWith("UTF-8", StringComparison.OrdinalIgnoreCase) ||
        locale.EndsWith("UTF8", StringComparison.OrdinalIgnoreCase);

    private static List<string> ParseEnvironmentNames(byte[] output)
    {
        var names = new List<string>();
        var seen = new HashSet<string>(StringComparer.Ordinal);
        foreach (var line in Encoding.UTF8.GetString(output).Split('\n'))
        {
            var entry = line.EndsWith('\r') ? line[..^1] : line;
            string? name = null;
            if (entry.StartsWith('-') && entry.Length > 1)
                name = entry[1..];
            else
            {
                var separator = entry.IndexOf('=');
                if (separator > 0)
                    name = entry[..separator];
            }

            if (name is not null && !name.Contains('\0') && seen.Add(name))
                names.Add(name);
        }
        return names;
    }

    private void EnsureAvailable()
    {
        if (_info.Availability == SessionHostAvailability.Available)
            return;
        throw new SessionHostException(new SessionHostError(SessionHostErrorCode.Unavailable,
            _info.Reason ?? "tmux session host is not initialized.", false));
    }

    private void SetAvailable(string? version) =>
        _info = new SessionHostInfo("tmux", version, SessionHostAvailability.Available, null,
            AvailableCapabilities);

    private void SetUnavailable(string reason, string? version = null) =>
        _info = new SessionHostInfo("tmux", version, SessionHostAvailability.Unavailable, reason,
            Array.Empty<string>());

    private static ArgumentException InvalidOptions() => new("Invalid tmux host options.");
}
