<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>false</IsTestProject>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Remove="xunit.v3" />
    <PackageReference Remove="Microsoft.Testing.Extensions.TrxReport" />
    <PackageReference Include="xunit.v3.extensibility.core" />
    <PackageReference Include="xunit.v3.assert" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Aiakos.Node\Aiakos.Node.csproj" />
  </ItemGroup>

</Project>
